terafoundation:
    environment: 'development'

    logging:
        - console

    connectors:
        elasticsearch:
            default:
                host:
                    - "localhost:9200"
                suggestCompression: true

teraslice:
    workers: 8
    master: true
    master_hostname: "127.0.0.1"
    name: "teraslice"
    hostname: "127.0.0.1"
    shutdown_timeout: 8000
